/**
 * Deep Research Workflow Domain Types
 *
 * Defines the types for a budget-aware deep research workflow that:
 * - Combines SERP, academic, and semantic search
 * - Extracts atomic claims from sources into a KnowledgeHypergraph
 * - Runs dialectical reasoning (thesis/negation/contradiction/sublation)
 * - Iteratively fills knowledge gaps via gap analysis loops
 * - Produces structured answers with full source traceability
 */

import type { ThesisLens } from './dialectical'

// ----- Budget -----

/**
 * Budget phases that control search depth and recursive learning behavior.
 * Transitions are based on percentage of maxBudgetUsd spent.
 */
export type BudgetPhase = 'full' | 'reduced' | 'minimal' | 'exhausted'

/**
 * Per-run budget tracking. Lives in LangGraph state and is updated
 * after every LLM call and search tool call.
 */
export interface RunBudget {
  maxBudgetUsd: number
  spentUsd: number
  spentTokens: number
  searchCallsUsed: number
  maxSearchCalls: number // derived from budget at creation
  llmCallsUsed: number
  phase: BudgetPhase
  maxRecursiveDepth: number // full=3, reduced=2, minimal=1, exhausted=0
  gapIterationsUsed: number
}

// ----- Sources -----

/**
 * Metadata for a fetched source document.
 * Stored as a 'source' node in the KnowledgeHypergraph.
 */
export interface SourceRecord {
  sourceId: string
  url: string
  title: string
  domain: string
  fetchedAtMs: number
  fetchMethod: 'read_url' | 'scrape_url' | 'parse_pdf' | 'crawl_website'
  contentLength: number
  contentHash: string // SHA-256 for dedup
  sourceType: 'web' | 'academic' | 'pdf' | 'crawled'
  relevanceScore?: number // 0-1 from relevance-first scoring
  /** Source quality score 0-1, computed from domain authority + date + citations (Phase 23) */
  sourceQualityScore?: number
  scholarMetadata?: {
    authors?: string[]
    year?: number
    citations?: number
    journal?: string
  }
}

/**
 * Result from the counterclaim adversarial agent (Phase 23)
 */
export interface CounterclaimResult {
  originalClaimId: string
  counterargument: string
  strength: 'strong' | 'moderate' | 'weak'
  evidenceBasis: string
}

/**
 * A chunk of a source document for claim extraction.
 */
export interface DocumentChunk {
  text: string
  section: string
  startOffset: number
  endOffset: number
  sourceId: string
}

// ----- Epistemic Metadata -----

/**
 * Evidence types for epistemic classification of claims.
 */
export type EvidenceType =
  | 'empirical'
  | 'theoretical'
  | 'anecdotal'
  | 'expert_opinion'
  | 'meta_analysis'
  | 'statistical'
  | 'review'

const VALID_EVIDENCE_TYPES: EvidenceType[] = [
  'empirical',
  'theoretical',
  'anecdotal',
  'expert_opinion',
  'meta_analysis',
  'statistical',
  'review',
]

/**
 * Validate and normalize an evidence type string.
 * Returns 'theoretical' as a safe default for unrecognized values.
 */
export function validateEvidenceType(raw: unknown): EvidenceType {
  if (typeof raw === 'string' && VALID_EVIDENCE_TYPES.includes(raw as EvidenceType)) {
    return raw as EvidenceType
  }
  return 'theoretical'
}

// ----- Claims -----

/**
 * An atomic claim extracted from a source document, ready for KG insertion.
 */
export interface ExtractedClaim {
  claimText: string
  confidence: number // 0-1
  evidenceType: EvidenceType
  sourceId: string
  sourceQuote?: string // exact span from source document
  pageOrSection?: string
  concepts: string[] // extracted concept names referenced by this claim
}

// ----- Search Planning -----

/**
 * A search plan generated by the planner agent or gap analysis.
 */
export interface SearchPlan {
  serpQueries: string[]
  scholarQueries: string[]
  semanticQueries: string[]
  rationale: string
  targetSourceCount: number
}

/**
 * Result from a single search execution.
 */
export interface SearchResult {
  url: string
  title: string
  snippet: string
  source: 'serp' | 'scholar' | 'semantic'
  relevanceScore?: number
  scholarMetadata?: SourceRecord['scholarMetadata']
}

// ----- Gap Analysis -----

/**
 * Result from the gap analysis agent examining the KG state.
 */
export interface GapAnalysisResult {
  gaps: GapItem[]
  overallCoverageScore: number // 0-1
  shouldContinue: boolean
  newSearchPlan?: SearchPlan
}

export interface GapItem {
  description: string
  missingEvidenceFor: string[] // claim IDs or concept names
  uncertaintyScore: number // 0-1
  suggestedQueries: string[]
  priority: 'high' | 'medium' | 'low'
}

// ----- Answer -----

/**
 * The final structured answer produced by the answer generation agent.
 */
export interface DeepResearchAnswer {
  directAnswer: string
  supportingClaims: Array<{
    claimText: string
    confidence: number
    sources: string[] // source URLs
    evidenceType: EvidenceType
  }>
  counterclaims: Array<{
    claimText: string
    confidence: number
    sources: string[]
  }>
  openUncertainties: string[]
  confidenceAssessment: {
    overall: number
    byTopic: Record<string, number>
  }
  citations: Array<{
    sourceId: string
    url: string
    title: string
    relevance: string
  }>
  knowledgeGraphSummary: {
    claimCount: number
    conceptCount: number
    contradictionCount: number
    resolvedCount: number
  }
}

// ----- KG Snapshots (for visualization) -----

/**
 * Lightweight snapshot of KG state captured after each major pipeline phase.
 * Enables timeline scrubbing in the DeepResearchViewer without duplicating the full graph.
 */
export interface KGSnapshot {
  stepIndex: number
  phase: string // which pipeline phase produced this
  timestamp: number
  stats: {
    claimCount: number
    conceptCount: number
    sourceCount: number
    mechanismCount: number
    contradictionCount: number
    communityCount: number
  }
  /** Delta from previous snapshot — used for diff highlighting in the viewer. */
  delta: {
    addedNodeIds: string[]
    supersededNodeIds: string[]
    addedEdgeKeys: string[] // "sourceId->targetId" format
    removedEdgeKeys: string[]
  }
}

// ----- Run Configuration -----

/**
 * Configuration for a deep research run, provided by the user at run creation.
 */
export interface DeepResearchRunConfig {
  query: string
  maxBudgetUsd: number
  searchDepth: 'shallow' | 'standard' | 'deep'
  includeAcademic: boolean
  includeSemanticSearch: boolean
  thesisLenses: ThesisLens[]
  /** Max outer gap-analysis → search loops (user-configurable, default 3) */
  maxGapIterations: number
  /** Max dialectical cycles per gap iteration (user-configurable, default 2) */
  maxDialecticalCycles: number
  /** Research mode: 'full' runs complete pipeline, 'quick' skips KG and gap analysis (Phase 25) */
  mode?: 'full' | 'quick'
}

/**
 * Default configuration for deep research runs.
 */
export function createDefaultDeepResearchConfig(): DeepResearchRunConfig {
  return {
    query: '',
    maxBudgetUsd: 10,
    searchDepth: 'standard',
    includeAcademic: true,
    includeSemanticSearch: true,
    thesisLenses: ['economic', 'systems', 'adversarial'],
    maxGapIterations: 3,
    maxDialecticalCycles: 2,
  }
}
