/**
 * Evidence Polling Loop
 *
 * Monitors predictions generated by the dialectical system and checks
 * for evidence that confirms or refutes them. This provides a feedback
 * loop for:
 *
 * 1. Validating synthesis predictions
 * 2. Detecting prediction failures early
 * 3. Triggering re-evaluation when evidence contradicts predictions
 * 4. Building empirical track record for thesis lenses
 *
 * The polling loop can run:
 * - During dialectical cycles (synchronous checking)
 * - As background tasks (asynchronous monitoring)
 */

import type {
  AgentConfig,
  AgentExecutionStep,
  DialecticalSessionId,
  ContradictionOutput,
  SublationOutput,
} from '@lifeos/agents'
import { executeAgentWithEvents, type AgentExecutionContext } from './langgraph/utils.js'
import { createLogger } from '../lib/logger.js'

const log = createLogger('EvidencePolling')

// ----- Configuration Constants -----

/** Default polling interval in milliseconds */
const DEFAULT_POLLING_INTERVAL_MS = 60000 // 1 minute
/** Maximum predictions to check per poll */
const MAX_PREDICTIONS_PER_POLL = 10
/** Default confidence threshold for marking prediction as validated */
const DEFAULT_VALIDATION_THRESHOLD = 0.7
/** Default confidence threshold for marking prediction as refuted */
const DEFAULT_REFUTATION_THRESHOLD = 0.7

// ----- Types -----

/**
 * A prediction to monitor
 */
export interface MonitoredPrediction {
  predictionId: string
  sessionId: DialecticalSessionId
  userId: string

  // Content
  text: string
  threshold: string // Success criteria
  sourceClaimId?: string
  sourceSynthesisCycle: number

  // Timing
  createdAtMs: number
  deadlineMs?: number // Optional deadline for the prediction
  lastCheckedMs?: number
  nextCheckMs?: number

  // Status
  status: 'PENDING' | 'VALIDATED' | 'REFUTED' | 'EXPIRED' | 'INCONCLUSIVE'
  confidence: number // How confident are we in the current status

  // Evidence history
  evidenceHistory: EvidenceCheck[]
}

/**
 * Result of checking a prediction against evidence
 */
export interface EvidenceCheck {
  checkId: string
  predictionId: string
  checkedAtMs: number

  // Evidence found
  evidenceSummary: string
  evidenceSources: EvidenceSource[]

  // Assessment
  supportScore: number // -1 to 1 (negative = refutes, positive = supports)
  confidence: number // 0-1
  reasoning: string

  // Cost
  tokensUsed: number
  estimatedCost: number
}

/**
 * Source of evidence
 */
export interface EvidenceSource {
  sourceType: 'WEB_SEARCH' | 'DEEP_RESEARCH' | 'USER_INPUT' | 'SYSTEM_DATA' | 'EXTERNAL_API'
  sourceId: string
  sourceUrl?: string
  excerpt: string
  relevanceScore: number
  retrievedAtMs: number
}

/**
 * Result of a polling cycle
 */
export interface EvidencePollingResult {
  predictionsChecked: number
  validated: MonitoredPrediction[]
  refuted: MonitoredPrediction[]
  inconclusive: MonitoredPrediction[]
  newContradictions: ContradictionOutput[]
  steps: AgentExecutionStep[]
  totalTokensUsed: number
  totalEstimatedCost: number
}

/**
 * Polling loop state
 */
export interface PollingLoopState {
  isRunning: boolean
  lastPollMs: number
  nextPollMs: number
  pollCount: number
  predictionsMonitored: number
  totalValidated: number
  totalRefuted: number
}

/**
 * Configuration for evidence polling
 */
export interface EvidencePollingConfig {
  pollingIntervalMs: number
  maxPredictionsPerPoll: number
  validationThreshold: number
  refutationThreshold: number
  enableWebSearch: boolean
  enableDeepResearch: boolean
  maxEvidenceSources: number
}

// ----- Main Functions -----

/**
 * Run a single evidence polling cycle
 */
export async function runEvidencePolling(
  predictions: MonitoredPrediction[],
  evidenceAgent: AgentConfig,
  execContext: AgentExecutionContext,
  config: EvidencePollingConfig,
  baseStepCount: number
): Promise<EvidencePollingResult> {
  log.info('Running evidence polling', { predictionCount: predictions.length })

  const pendingPredictions = predictions.filter((p) => p.status === 'PENDING')
  const predictionsToCheck = pendingPredictions.slice(0, config.maxPredictionsPerPoll)

  if (predictionsToCheck.length === 0) {
    log.info('No pending predictions to check')
    return {
      predictionsChecked: 0,
      validated: [],
      refuted: [],
      inconclusive: [],
      newContradictions: [],
      steps: [],
      totalTokensUsed: 0,
      totalEstimatedCost: 0,
    }
  }

  // Check predictions in parallel (with limit)
  const checkPromises = predictionsToCheck.map(async (prediction, idx) => {
    return checkPrediction(prediction, evidenceAgent, execContext, config, baseStepCount + idx)
  })

  const results = await Promise.all(checkPromises)
  const successfulResults = results.filter((r) => r !== null)

  // Categorize results
  const validated: MonitoredPrediction[] = []
  const refuted: MonitoredPrediction[] = []
  const inconclusive: MonitoredPrediction[] = []
  const newContradictions: ContradictionOutput[] = []
  const steps: AgentExecutionStep[] = []

  for (const result of successfulResults) {
    if (!result) continue

    steps.push(result.step)

    // Update prediction status based on evidence
    const updatedPrediction = updatePredictionStatus(result.prediction, result.check, config)

    switch (updatedPrediction.status) {
      case 'VALIDATED':
        validated.push(updatedPrediction)
        break
      case 'REFUTED':
        refuted.push(updatedPrediction)
        // Create contradiction for refuted prediction
        newContradictions.push(createRefutationContradiction(updatedPrediction, result.check))
        break
      default:
        inconclusive.push(updatedPrediction)
        break
    }
  }

  const totalTokensUsed = steps.reduce((sum, s) => sum + s.tokensUsed, 0)
  const totalEstimatedCost = steps.reduce((sum, s) => sum + s.estimatedCost, 0)

  log.info('Evidence polling complete', {
    validated: validated.length,
    refuted: refuted.length,
    inconclusive: inconclusive.length,
  })

  return {
    predictionsChecked: successfulResults.length,
    validated,
    refuted,
    inconclusive,
    newContradictions,
    steps,
    totalTokensUsed,
    totalEstimatedCost,
  }
}

/**
 * Check a single prediction against available evidence
 */
async function checkPrediction(
  prediction: MonitoredPrediction,
  evidenceAgent: AgentConfig,
  execContext: AgentExecutionContext,
  config: EvidencePollingConfig,
  stepNumber: number
): Promise<{
  prediction: MonitoredPrediction
  check: EvidenceCheck
  step: AgentExecutionStep
} | null> {
  try {
    const prompt = buildEvidenceCheckPrompt(prediction, config)

    const step = await executeAgentWithEvents(
      evidenceAgent,
      prompt,
      {
        predictionId: prediction.predictionId,
        phase: 'evidence_polling',
        enableWebSearch: config.enableWebSearch,
        enableDeepResearch: config.enableDeepResearch,
      },
      execContext,
      { stepNumber }
    )

    const check = parseEvidenceCheckOutput(step.output, prediction.predictionId, step)

    return { prediction, check, step }
  } catch (error) {
    log.error('Failed to check prediction', error, { predictionId: prediction.predictionId })
    return null
  }
}

/**
 * Update prediction status based on evidence check
 */
function updatePredictionStatus(
  prediction: MonitoredPrediction,
  check: EvidenceCheck,
  config: EvidencePollingConfig
): MonitoredPrediction {
  const newHistory = [...prediction.evidenceHistory, check]

  // Calculate cumulative support score (weighted by confidence)
  let totalWeightedSupport = 0
  let totalConfidence = 0
  for (const c of newHistory) {
    totalWeightedSupport += c.supportScore * c.confidence
    totalConfidence += c.confidence
  }
  const cumulativeSupport = totalConfidence > 0 ? totalWeightedSupport / totalConfidence : 0

  // Determine status
  let newStatus: MonitoredPrediction['status'] = 'PENDING'
  let newConfidence = check.confidence

  if (cumulativeSupport >= config.validationThreshold) {
    newStatus = 'VALIDATED'
    newConfidence = Math.min(1, cumulativeSupport)
  } else if (cumulativeSupport <= -config.refutationThreshold) {
    newStatus = 'REFUTED'
    newConfidence = Math.min(1, Math.abs(cumulativeSupport))
  } else if (prediction.deadlineMs && Date.now() > prediction.deadlineMs) {
    newStatus = 'EXPIRED'
    newConfidence = 0.5
  } else if (newHistory.length >= 5 && Math.abs(cumulativeSupport) < 0.2) {
    newStatus = 'INCONCLUSIVE'
    newConfidence = 0.3
  }

  return {
    ...prediction,
    status: newStatus,
    confidence: newConfidence,
    lastCheckedMs: check.checkedAtMs,
    nextCheckMs: Date.now() + DEFAULT_POLLING_INTERVAL_MS,
    evidenceHistory: newHistory,
  }
}

/**
 * Create a contradiction for a refuted prediction
 */
function createRefutationContradiction(
  prediction: MonitoredPrediction,
  check: EvidenceCheck
): ContradictionOutput {
  return {
    id: `refute_${prediction.predictionId}_${Date.now()}`,
    type: 'DIACHRONIC', // Prediction made in past contradicted by present evidence
    severity: 'HIGH',
    actionDistance: 1, // Refuted predictions are immediately actionable
    participatingClaims: [prediction.predictionId, check.checkId],
    trackerAgent: 'evidence_polling',
    description: `Prediction "${prediction.text.substring(0, 100)}..." was refuted by evidence: ${check.reasoning.substring(0, 200)}`,
  }
}

// ----- Prompt Builder -----

function buildEvidenceCheckPrompt(
  prediction: MonitoredPrediction,
  config: EvidencePollingConfig
): string {
  const previousChecks = prediction.evidenceHistory.slice(-3)
  const previousEvidence =
    previousChecks.length > 0
      ? `\nPREVIOUS CHECKS:\n${previousChecks.map((c) => `- ${c.checkedAtMs}: ${c.supportScore >= 0 ? 'Supporting' : 'Refuting'} (${c.confidence}): ${c.reasoning.substring(0, 100)}`).join('\n')}`
      : ''

  return `You are an evidence checker evaluating whether a prediction has been validated or refuted.

PREDICTION:
"${prediction.text}"

SUCCESS THRESHOLD:
${prediction.threshold}

CREATED: ${new Date(prediction.createdAtMs).toISOString()}
${prediction.deadlineMs ? `DEADLINE: ${new Date(prediction.deadlineMs).toISOString()}` : ''}
${previousEvidence}

Your task:
1. Search for relevant evidence (${config.enableWebSearch ? 'web search enabled' : 'limited to context'})
2. Assess whether the evidence SUPPORTS or REFUTES the prediction
3. Rate your confidence in this assessment

Respond with JSON:
{
  "evidenceSummary": "Brief summary of evidence found",
  "evidenceSources": [
    {
      "sourceType": "WEB_SEARCH|DEEP_RESEARCH|USER_INPUT|SYSTEM_DATA|EXTERNAL_API",
      "sourceId": "unique identifier",
      "sourceUrl": "optional URL",
      "excerpt": "relevant quote or data",
      "relevanceScore": 0.8
    }
  ],
  "supportScore": 0.5,  // -1.0 (strongly refutes) to 1.0 (strongly supports), 0 = neutral
  "confidence": 0.7,    // 0-1, how confident in this assessment
  "reasoning": "Explanation of why evidence supports or refutes the prediction"
}

Guidelines:
- supportScore near 0 means evidence is neutral or irrelevant
- Only assign high confidence if evidence directly addresses the prediction
- Consider whether the threshold criteria are met, not just directional accuracy
- Account for timing - evidence must be from after the prediction was made to be relevant`
}

// ----- Parsers -----

function parseEvidenceCheckOutput(
  output: string,
  predictionId: string,
  step: AgentExecutionStep
): EvidenceCheck {
  const now = Date.now()

  try {
    const jsonMatch = output.match(/\{[\s\S]*\}/)?.[0]
    if (jsonMatch) {
      const parsed = JSON.parse(jsonMatch)
      return {
        checkId: `check_${predictionId}_${now}`,
        predictionId,
        checkedAtMs: now,
        evidenceSummary: parsed.evidenceSummary ?? 'No summary provided',
        evidenceSources: (parsed.evidenceSources ?? []).map((s: EvidenceSource) => ({
          ...s,
          retrievedAtMs: now,
        })),
        supportScore: Math.max(-1, Math.min(1, parsed.supportScore ?? 0)),
        confidence: Math.max(0, Math.min(1, parsed.confidence ?? 0.5)),
        reasoning: parsed.reasoning ?? 'No reasoning provided',
        tokensUsed: step.tokensUsed,
        estimatedCost: step.estimatedCost,
      }
    }
  } catch (error) {
    log.warn('Failed to parse evidence check JSON', { error })
  }

  // Return neutral check if parsing fails
  return {
    checkId: `check_${predictionId}_${now}`,
    predictionId,
    checkedAtMs: now,
    evidenceSummary: 'Failed to parse evidence check',
    evidenceSources: [],
    supportScore: 0,
    confidence: 0.1,
    reasoning: 'Evidence check output could not be parsed',
    tokensUsed: step.tokensUsed,
    estimatedCost: step.estimatedCost,
  }
}

// ----- Utility Functions -----

/**
 * Extract predictions from synthesis output
 */
export function extractPredictionsFromSynthesis(
  synthesis: SublationOutput,
  sessionId: DialecticalSessionId,
  userId: string,
  cycleNumber: number
): MonitoredPrediction[] {
  return (synthesis.newPredictions ?? []).map((p, idx) => ({
    predictionId: p.id || `pred_${cycleNumber}_${idx}`,
    sessionId,
    userId,
    text: p.text,
    threshold: p.threshold,
    sourceSynthesisCycle: cycleNumber,
    createdAtMs: Date.now(),
    status: 'PENDING' as const,
    confidence: 0,
    evidenceHistory: [],
  }))
}

/**
 * Create default evidence polling config
 */
export function createDefaultPollingConfig(): EvidencePollingConfig {
  return {
    pollingIntervalMs: DEFAULT_POLLING_INTERVAL_MS,
    maxPredictionsPerPoll: MAX_PREDICTIONS_PER_POLL,
    validationThreshold: DEFAULT_VALIDATION_THRESHOLD,
    refutationThreshold: DEFAULT_REFUTATION_THRESHOLD,
    enableWebSearch: true,
    enableDeepResearch: false, // Deep research is expensive
    maxEvidenceSources: 5,
  }
}

/**
 * Get predictions due for checking
 */
export function getPredictionsDueForCheck(
  predictions: MonitoredPrediction[]
): MonitoredPrediction[] {
  const now = Date.now()
  return predictions.filter((p) => {
    if (p.status !== 'PENDING') return false
    if (!p.nextCheckMs) return true // Never checked
    return p.nextCheckMs <= now
  })
}

// ----- Exports -----

export {
  DEFAULT_POLLING_INTERVAL_MS,
  MAX_PREDICTIONS_PER_POLL,
  DEFAULT_VALIDATION_THRESHOLD,
  DEFAULT_REFUTATION_THRESHOLD,
}
